
name: build

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    env:
      PROG_NAME: citest
      BIN_NAME: citest-${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-24.04
          - macos-15
          - windows-2025

    steps:
      - uses: actions/checkout@v4
      - uses: haskell-actions/setup@v2
        with:
          ghc-version: '9.4'
      - run: |
          cabal build
      - name: build (unix)
        if: ${{ !contains(matrix.os, 'windows') }}
        run: |
          cp $( cabal list-bin ${{ env.PROG_NAME }} ) ${{ env.BIN_NAME }}
          xz -9 -k ${{ env.BIN_NAME }}
          ls -l ${{ env.BIN_NAME }} ${{ env.BIN_NAME }}.xz
          md5sum ${{ env.BIN_NAME }} ${{ env.BIN_NAME }}.xz
      - name: build (clippyos)
        if: ${{ contains(matrix.os, 'windows') }}
        run: |
          cp $( cabal list-bin ${{ env.PROG_NAME }} ) ${{ env.BIN_NAME }}.exe
          xz -9 -k ${{ env.BIN_NAME }}.exe
          ls -l ${{ env.BIN_NAME }}.exe ${{ env.BIN_NAME }}.exe.xz
          md5sum ${{ env.BIN_NAME }}.exe ${{ env.BIN_NAME }}.exe.xz
      - name: release (unix)
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ env.BIN_NAME }}.xz
      - name: release (clippyos)
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ env.BIN_NAME }}.exe.xz
