
name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    name: build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    env:
      PROG_NAME: citest
      BIN_NAME: citest-${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-24.04
          - macos-15
          - windows-2025
    steps:
      - uses: actions/checkout@v4
      - uses: haskell-actions/setup@v2
        with:
          ghc-version: '9.4'
      - run: |
          cabal build
          cp `cabal list-bin $PROG_NAME` $BIN_NAME
          xz -9 -k $BIN_NAME
          ls -l $BIN_NAME $BIN_NAME.xz
          md5sum $BIN_NAME $BIN_NAME.xz
